---
daemon_sleep_seconds: 60
global_ignore_list:
  - .arcconfig
  - .arclint
mediawiki_username: JSS 9
repositories_root: /home/jss9/.local/share/git-sync/repos

repos:
  - name: wikipedia-lua
    project:
      code: bg
      family: wikipedia
    namespace: Module
    file_regex: .*
    regex_nocase: false
    ignore_list: []
    force_extension: lua
  - name: wikipedia-spam
    project:
      code: bg
      family: wikipedia
    namespace: MediaWiki
    file_regex: ^Spam
    regex_nocase: false
    ignore_list: []
    force_extension: null
  - name: wikipedia-tbl
    project:
      code: bg
      family: wikipedia
    namespace: MediaWiki
    file_regex: ^Title
    regex_nocase: false
    ignore_list: []
    force_extension: null
  - name: wikipedia-ui
    project:
      code: bg
      family: wikipedia
    namespace: MediaWiki
    file_regex: (^gadgets?-|\.(css|js)\b)
    regex_nocase: true
    ignore_list: []
    force_extension: null

usermap:
  Iliev:
    author: Luchesar ILIEV
    email: luchesar.iliev@gmail.com
  Borislav:
    author: Borislav
    email: b.manolov@gmail.com
  Петър Петров:
    author: petar-petrov-w
    email: 65830242+petar-petrov-w@users.noreply.github.com
